name: PHP Composer
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2'] # Testing on multiple PHP versions
    steps:
    - uses: actions/checkout@v4

    # Set up PHP version
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, phpunit
    
    # Validate composer.json (strict mode)
    - name: Validate composer.json
      run: composer validate --strict

    # Validate composer.lock (this will automatically happen when installing dependencies)
    - name: Validate composer.lock
      run: composer validate --strict

    # Cache Composer dependencies
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php }}-
          ${{ runner.os }}-php-

    # Install dependencies
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Analyze PHP code (optional)
    - name: Analyze code with PHPStan
      run: vendor/bin/phpstan analyse

    # Run tests
    - name: Run test suite
      run: composer run-script test

  # Conditional publication (only on push to main)
  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Publish package
      run: composer publish --access-token ${{ secrets.COMPOSER_AUTH }}

