name: PHP Composer
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2'] # Prueba en múltiples versiones de PHP
    steps:
    - uses: actions/checkout@v4

    # Configura la versión de PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, phpunit

    # Validar composer.json y composer.lock
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    # Cache de dependencias de Composer
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php }}-

    # Instalar dependencias
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Validar código PHP (opcional)
    - name: Analyze code with PHPStan
      run: vendor/bin/phpstan analyse

    # Ejecutar pruebas
    - name: Run test suite
      run: composer run-script test

    # Opcional: Subir reporte de cobertura
    # - name: Upload code coverage
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: coverage.xml
    #     flags: unittests

  # Publicación condicional (opcional)
  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Publish package
      run: composer publish --access-token ${{ secrets.COMPOSER_AUTH }}
